services:
  express-app:
    image: ikylioss/3.1expressapp
    ports:
      - 8080:8080
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_INCLUDE=express-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: express-app
    privileged: true