services:
  express-app:
    image: ikylioss/3.1expressapp
    build: .
    ports:
    - 8080:8080
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_INCLUDE=express-app
    volumes:
      - /var/run/docker.sock/var/run/docker.sock
    container_name: watchtower